### ISSUE TITLE
Found a lot of duplicate songs.

### ISSUE THREAD

**Issue by lionants02** [SpectrixDev/bot-saber#3]
I really like the detailed display of the bot. 
I really liked the detailed display of the bot, but when I b! Song didn't find the song I wanted.

BTS – Dynamite
Can I specify the Mapper or the key?

Thank you.

**Comment by SpectrixDev** [comment]
This is due to the search API finding the most relevant result first. We will implement a system in which you can search for a beatmap via either ID or name.

For example, `b!map id da60` and `b!map name Midnight Lady`.

Thanks for the suggestion, we'll get to it and include it in our rewrite of both the song and profile commands!

**Comment by SpectrixDev** [comment]
This has been implemented in the Python rewrite. Sorry for the big delay, it shouldn't happen again.
